actionbar: true
chat: true
sound: true

message-1-argument: "<green>Your ping is <#0ecc1e>%ping%ms</green>"
message-2-argument: "<green>%player%'s ping is <#0ecc1e>%ping%ms</green>"
player-not-found-message: "<red>The player does not exist on the server"
reload-message: "<green>Configuration reloaded."

sounds:
  ping-check: "ENTITY_EXPERIENCE_ORB_PICKUP"
  player-not-found: "entity.villager.trade"
  config-reload: "BLOCK_NOTE_BLOCK_PLING"